#version 450

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

struct Light {
    vec4 position;      // w = light type (0: Point, 1: Spot, 2: Directional)
    vec4 color;         // rgb + intensity
    vec4 direction;     // spot / directional
    float radius;       // spot / point
    float innerCone;    // spot
    float outerCone;    // spot
    uint shadowIndex;   // spot / directional
    mat4 lightVP;       // spot / directional
};

layout (set = 0, binding = 0) uniform PerFrameUniforms { 
    // Camera
    mat4 view;
    mat4 proj;
    mat4 invView;
    mat4 invProj;
    vec4 position;
    float near;
    float far;
    // Settings
    float exposure;
    float gamma;
    float ambientIntensity;
    uint lightCount;
    ivec2 screenSize;
    ivec2 shadowSize;
    // Light culling
    uint tileSize;
    uint tilesX;
    uint tilesY;
    uint maxLightsPerTile;
} uniforms;

layout (set = 0, binding = 1) readonly buffer LightBuffer { 
    Light lights[]; 
} lightBuffer;
layout (set = 2, binding = 0) buffer LightIndexBuffer {
    uint indices[];
} indexBuffer;
layout (set = 2, binding = 1) buffer TileCountBuffer {
    uint tileCounts[];
} tileCountBuffer;

shared vec4 sFrustumPlanes[6];

vec4 MakePlane(vec3 a, vec3 b, vec3 c)
{
    vec3 n = normalize(cross(b - a, c - a));
    float d = -dot(n, a);
    return vec4(n, d);
}

void CalculateTileFrustum(uint tileX, uint tileY, out vec4 planes[6])
{
    // NOTE: Flip y coordinate because Vulkan has NDC bottom as y=1, and glm has NDC top as y=1
    tileY = gl_NumWorkGroups.y - tileY - 1;

    float left   = (float(tileX * uniforms.tileSize) / uniforms.screenSize.x) * 2.0 - 1.0;
    float right  = (float(min((tileX + 1) * uniforms.tileSize, uniforms.screenSize.x)) / uniforms.screenSize.x) * 2.0 - 1.0;
    float bottom = 1.0 - (float(tileY * uniforms.tileSize) / uniforms.screenSize.y) * 2.0;
    float top    = 1.0 - (float(min((tileY + 1) * uniforms.tileSize, uniforms.screenSize.y)) / uniforms.screenSize.y) * 2.0;

    vec2 ndc[4] = {
        vec2(left, top),
        vec2(right, top),
        vec2(left, bottom),
        vec2(right, bottom)
    };

    mat4 inverseProjection = inverse(uniforms.proj);

    vec3 viewNear[4];
    vec3 viewFar[4];
    for (uint i = 0; i < 4; i++) {
        vec4 clipNear = vec4(ndc[i], 0.0, 1.0);
        vec4 vn = inverseProjection * clipNear;
        viewNear[i] = vn.xyz / vn.w;

        vec4 clipFar = vec4(ndc[i], 1.0, 1.0);
        vec4 vf = inverseProjection * clipFar;
        viewFar[i] = vf.xyz / vf.w;
    }

    planes[0] = MakePlane(vec3(0.0), viewNear[0], viewNear[2]);   // Left
    planes[1] = MakePlane(vec3(0.0), viewNear[3], viewNear[1]);   // Right
    planes[2] = MakePlane(vec3(0.0), viewNear[1], viewNear[0]);   // Top
    planes[3] = MakePlane(vec3(0.0), viewNear[2], viewNear[3]);   // Bottom
    planes[4] = MakePlane(viewNear[0], viewNear[1], viewNear[2]); // Near
    planes[5] = MakePlane(viewFar[0], viewFar[2], viewFar[1]);    // Far
}

bool SphereInFrustum(vec4 planes[6], vec3 centre, float radius)
{
    for (uint i = 0; i < 6; i++) {
        float dist = dot(planes[i].xyz, centre) + planes[i].w;
        if (dist < -radius) return false;
    }
    return true;
}

void main() 
{
    uint tileX = gl_WorkGroupID.x;
    uint tileY = gl_WorkGroupID.y;
    uint tileIndex = tileY * gl_NumWorkGroups.x + tileX;
    uint localIndex = gl_LocalInvocationIndex;
    uint offset = uniforms.maxLightsPerTile * tileIndex;

    uint pixelX = tileX * uniforms.tileSize + gl_LocalInvocationID.x;
    uint pixelY = tileY * uniforms.tileSize + gl_LocalInvocationID.y;

    for (uint i = localIndex; i < uniforms.lightCount; i += (gl_WorkGroupSize.x * gl_WorkGroupSize.y)) {
        Light light = lightBuffer.lights[i];
        uint type = uint(light.position.w);
        bool affects = false;

        if (type == 2) {
            // Directional always affects
            affects = true;
        } else {
            // Point and Spot - sphere / frustum intersection
            vec3 centre = light.position.xyz;
            float radius = light.radius;

            if (type == 1) {
                // For spot lights we move the bounding sphere to a better position
                vec3 dir = light.direction.xyz;
                centre = light.position.xyz - dir * (radius * 0.5);
                radius *= 0.5;
            }

            // Intersection check
            vec4 clipPos = uniforms.proj * uniforms.view * vec4(centre, 1.0);
            float lightNDC = clipPos.z / clipPos.w;
            lightNDC = lightNDC * 0.5 + 0.5;
            float radiusNDC = radius / clipPos.w;
            // if (clipPos.w < 0.0) {
                vec3 centreView = (uniforms.view * vec4(centre, 1.0)).xyz;
                if (SphereInFrustum(sFrustumPlanes, centreView, radius)) {
                    affects = true;
                }
            // }
        }

        if (affects) {
            // Atomically increment tileCounts, and get a slot into lightIndices
            uint slot = atomicAdd(tileCountBuffer.tileCounts[tileIndex], 1);
            if (slot < uniforms.maxLightsPerTile) {
                indexBuffer.indices[offset + slot] = i;
            }
        }
    }
}
