#version 450

#define MAX_MIPS 16

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout (push_constant) uniform PushConstants {
    uint srcIndex;
    uint srcWidth;
    uint srcHeight;
    uint dstIndex;
    uint dstWidth;
    uint dstHeight;
} constants;

layout (set = 0, binding = 0, rgba8) uniform readonly image2D srcImage[MAX_MIPS];
layout (set = 0, binding = 1, rgba8) uniform writeonly image2D dstImage[MAX_MIPS];

void main() {
    ivec2 dstCoord = ivec2(gl_GlobalInvocationID.xy);
    if (dstCoord.x >= constants.dstWidth || dstCoord.y >= constants.dstHeight) {
        return;
    }

    vec3 normal = vec3(0.0, 0.0, 1.0);
    if (constants.srcIndex == 0) { // Upscale
        // Bilinear upscale
        vec2 srcUV = ((vec2(dstCoord) + 0.5) * vec2(constants.srcWidth, constants.srcHeight) / vec2(constants.dstWidth, constants.dstHeight)) - 0.5;
        ivec2 texelCoord = ivec2(floor(srcUV));
        vec2 fractional = fract(srcUV);

        ivec2 texelMax = ivec2(constants.srcWidth - 1, constants.srcHeight - 1);
        ivec2 tlTexel = clamp(texelCoord + ivec2(0, 0), ivec2(0), texelMax);
        ivec2 trTexel = clamp(texelCoord + ivec2(1, 0), ivec2(0), texelMax);
        ivec2 blTexel = clamp(texelCoord + ivec2(0, 1), ivec2(0), texelMax);
        ivec2 brTexel = clamp(texelCoord + ivec2(1, 1), ivec2(0), texelMax);

        vec3 tl = imageLoad(srcImage[constants.srcIndex], tlTexel).xyz * 2.0 - 1.0;
        vec3 tr = imageLoad(srcImage[constants.srcIndex], trTexel).xyz * 2.0 - 1.0;
        vec3 bl = imageLoad(srcImage[constants.srcIndex], blTexel).xyz * 2.0 - 1.0;
        vec3 br = imageLoad(srcImage[constants.srcIndex], brTexel).xyz * 2.0 - 1.0;

        vec3 mixed = mix(mix(tl, tr, fractional.x), mix(bl, br, fractional.x), fractional.y);

        // Renormalize
        float len = length(mixed);
        normal = (len > 0.0001) ? mixed / len : vec3(0.0, 0.0, 1.0);
    } else { // Downscale
        ivec2 srcCoord = dstCoord * 2;

        vec3 tl = imageLoad(srcImage[constants.srcIndex], srcCoord + ivec2(0, 0)).xyz * 2.0 - 1.0;
        vec3 tr = imageLoad(srcImage[constants.srcIndex], srcCoord + ivec2(1, 0)).xyz * 2.0 - 1.0;
        vec3 bl = imageLoad(srcImage[constants.srcIndex], srcCoord + ivec2(0, 1)).xyz * 2.0 - 1.0;
        vec3 br = imageLoad(srcImage[constants.srcIndex], srcCoord + ivec2(1, 1)).xyz * 2.0 - 1.0;

        vec3 average = (tl + tr + bl + br) / 4;

        // Renormalize
        float len = length(average);
        normal = (len > 0.0001) ? average / len : vec3(0.0, 0.0, 1.0);
    }

    vec4 outNormal = vec4(normal * 0.5 + 0.5, 1.0);
    imageStore(dstImage[constants.dstIndex], dstCoord, outNormal);
}
